// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCeXZ_T9bJ9k07sMq_nRf-chSDnPHd9i0',
    appId: '1:865838288948:web:92da26b19ccd2817343a61',
    messagingSenderId: '865838288948',
    projectId: 'chatapp-12a60',
    authDomain: 'chatapp-12a60.firebaseapp.com',
    storageBucket: 'chatapp-12a60.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmF2ZCiooIsNXQ3IfymiqfpL1Dlkdw8AM',
    appId: '1:865838288948:android:9293723b841aa414343a61',
    messagingSenderId: '865838288948',
    projectId: 'chatapp-12a60',
    storageBucket: 'chatapp-12a60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpY2nlRbZnCOp3GKnltJefgV9YvTuQ5FE',
    appId: '1:865838288948:ios:7e5534c61364578f343a61',
    messagingSenderId: '865838288948',
    projectId: 'chatapp-12a60',
    storageBucket: 'chatapp-12a60.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpY2nlRbZnCOp3GKnltJefgV9YvTuQ5FE',
    appId: '1:865838288948:ios:425a2fd96070a688343a61',
    messagingSenderId: '865838288948',
    projectId: 'chatapp-12a60',
    storageBucket: 'chatapp-12a60.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
